### ISSUE TITLE
have built sites persist through box rebuilds

### ISSUE THREAD

**Issue by pirog** [kalamuna/kalastack#19]

**Comment by patcon** [comment]
In the ariadne project, we used a convention where a basic setup recipe would play it safe by default, and not override, then that it would delete the user directories if a certain node attribute was set to `true`

https://github.com/myplanetdigital/vagrant-ariadne/blob/master/cookbooks-override/ariadne/recipes/default.rb#L59-L79

This node attribute was set in the vagrantfile if a specific environment variable had been set:
https://github.com/myplanetdigital/vagrant-ariadne/blob/master/Vagrantfile#L108-L109

The same could be done with Puppet's facter. Basically, `vagrant provision` would never wipe anything, but this would:

```
clean=true vagrant provision
```

Since, the linked recipe code was executed early in the chef run, the rest of the chef run would execute as if it was the first one, since it wouldn't see any project directories created (there was simple conditional logic elsewhere to ensure this)

Anyhow, just a suggestion :)

**Comment by patcon** [comment]
In unixy fashion, this could be implemented as a vagrant plugin. Basically, you would set the trigger envvar in the Vagrantfile, and if that existed, it would merge a boolean value into chef/puppet/whatever's facter equivalent that could be referenced in your custom modules.

**Comment by pirog** [comment]
now that we are just sticking with ubuntu 1204 this functionality is not as critical as it would have been had we allowed the user to bounce between stacks. might want to move this to the proviso issues queue?

**Comment by pirog** [comment]
there might be a quick and dirty way to do this so im going to reopen this.

maybe put mysql databases and vhosts in a vagrant shared folder?

**Comment by pirog** [comment]
in beta6 if you spin up a site and then have to rebuild your box you dont have to rebuild the site

**Comment by pirog** [comment]
quick and dirty way is a no go. this should be a vagrant plugin.

**Comment by patcon** [comment]
Never tried it, but what about the approach of syncing the folder that stores the mysql db files, so that they persist?
http://stackoverflow.com/questions/484750/restoring-mysql-database-from-physical-files

EDIT: Also related:
https://groups.google.com/forum/#!msg/vagrant-up/s5DheLw-v5Q/o-irqCTs2xkJ
